### ISSUE TITLE
Break out VSYS?

### ISSUE THREAD

**Issue by nevercast** [AlexKlimaj/LiPow-Hardware#1]
Hello Alex,

I really like this board design and I've checked out your product on Tindie. The BQ25703ARSNR is a very nice chip too.

I'm hoping you might consider another product, or a revision to this product, where VSYS is provided on a board header also so that I may use LiPow as both a charger and power delivery to my system.

I would like to use something similar to LiPow for in-system charging of my robot project as well as powering the system. The BQ25703ARSNR has some nice features included powering the system from charge cable and supplimenting with battery power when available.

Since the STM32G0 occupies the I2C and having two hosts talk to the BQ25703ARSNR could be bad, I would consider making the UART protocol machine readable, but that would be a software adaption and I see that is open source.

Do you have any plans in the future to provide system power from the LiPow?

Thanks again for your time on this project, it really is a nicely done board.

**Comment by AlexKlimaj** [comment]
Hi, thanks for the feedback. I don't have any plans at the moment for a revision of LiPow. I do have a board I've designed that is purely a breakout for the BQ25703ARSNR. It is sitting in a box waiting to be assembled. Unfortunately I didn't break out VSYS on that either. But there are lots of bulk capacitors on VSYS you could tack onto. Same with LiPow. 
https://github.com/AlexKlimaj/BQ25703A_Module

It would be pretty easy to improve the firmware to have everything controllable over the UART.

**Comment by nevercast** [comment]
Hello again Alex,

Thanks for the link to your breakout board. Are the only board layout files in the manufacturing docs? Do you have gerbers? 

Kind regards

**Comment by AlexKlimaj** [comment]
I can send you the gerbers if you are interested in building your own. I could also send you PCBs. I have PCBs and parts to build them up, just haven't had the time. I plan on selling them on tindie.

**Comment by nevercast** [comment]
I would be interested in building my own, and probably merging the module with existing hardware that I have for driving motors / servos. Shall we continue this via email?

**Comment by x893** [comment]
Hello Alex,
Thank you for LiPow and BQ25703 boards design. I want order boards for soldering (i have BQ... and other chips). Can you commit or send me directly gerber files ?

Best regards
Mitek

**Comment by AlexKlimaj** [comment]
@x893 send me an email at alex@arkelectron.com

**Comment by x893** [comment]
@AlexKlimaj please send to x893.00@gmail.com
Thanks
