### ISSUE TITLE
What different BAT pin and CELL_4S/CELL_3S pin?

### ISSUE THREAD

**Issue by jecelyin** [AlexKlimaj/LiPow-Hardware#2]
Hi,
   I use 3s of 18650 batteries to charge, how to connect is correct? 

Thanks!

---------- BAT or CELL_3S ?
🔋
---------- CELL_2S
🔋
---------- CELL_1S
🔋
---------- GND

**Comment by AlexKlimaj** [comment]
You need cell 3s connected to the 3s input and BAT to charge. If it is just connected to the balance port, it will only balance.

**Comment by jecelyin** [comment]
---------- BAT pin and CELL_3S pin connect to here?
🔋
---------- CELL_2S
🔋
---------- CELL_1S
🔋
---------- GND

Can you tell me the schematic diagram of the battery pack?

**Comment by AlexKlimaj** [comment]
That is correct.

**Comment by jecelyin** [comment]
Thanks
