### ISSUE TITLE
No Gerber file?

### ISSUE THREAD

**Issue by bigjoncoop** [AlexKlimaj/LiPow-Hardware#3]
I see you have the BOM files but I do not see a gerber file for the PCB...

The schematics or just PDF files. So I'm not quite sure what the purpose of the GitHub is for?

Anyone that's reading this I'll go ahead and spend a bunch of hours recreating the schematics and designing a new pcb and uploads all the files, including a gerber file. If the BOM changes due to the chip shortage at the moment I'll make a note.

**Comment by AlexKlimaj** [comment]
Yes that is intentional.

**Comment by Patronics** [comment]
@bigjoncoop did you ever get around to making your own variant of the design for this, or find some other open source project that's equivalent?
